/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Brookhuis
 * Created: 15-jan-2016
 */

CREATE DATABASE rapunzel;
USE rapunzel;

CREATE TABLE user(
userId INT NOT NULL AUTO_INCREMENT,
username VARCHAR(30) NOT NULL,
password VARCHAR(255) NOT NULL,
mail VARCHAR(50) NULL,
type ENUM('user', 'admin') NOT NULL DEFAULT 'user',
CONSTRAINT PK_USER PRIMARY KEY (userId)
)ENGINE=INNODB;

CREATE TABLE list(
listId INT NOT NULL AUTO_INCREMENT,
listname VARCHAR(100) NOT NULL,
CONSTRAINT PK_LIST PRIMARY KEY (listId)
)ENGINE=INNODB;

CREATE TABLE list_user(
listId INT NOT NULL,
userId INT NOT NULL,
isFav BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT PK_LIST_USER PRIMARY KEY (listId, userId),
CONSTRAINT FK_LIST_USER_LIST FOREIGN KEY (listId) REFERENCES LIST(listId)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_LIST_USER_USER FOREIGN KEY (userId) REFERENCES USER(userId)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB;

CREATE TABLE item(
itemId INT NOT NULL AUTO_INCREMENT,
listId INT NOT NULL,
itemname VARCHAR(40) NULL,
itemtext TEXT NULL,
CONSTRAINT PK_ITEM PRIMARY KEY (itemId),
CONSTRAINT FK_ITEM_LIST FOREIGN KEY (listId) REFERENCES LIST(listId)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=INNODB;